{
 "title": "{dashboard_title}",
 "tags": [
  "ran",
  "edge",
  "autoscaling"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "User simulation ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users per Cell",
   "type": "timeseries",
   "description": "Users per Cell",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ran_users_per_cell", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data rate per Cell",
   "type": "timeseries",
   "description": "Data rate per Cell",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "ran_data_rate_per_cell_mbps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users per Edge Nodes",
   "type": "timeseries",
   "description": "Users per Edge Nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(edge_node) (ran_users_per_cell)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data rate per Edge Node",
   "type": "timeseries",
   "description": "Data rate per Edge Node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(edge_node) (ran_data_rate_per_cell_mbps)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas: desired vs current",
   "type": "timeseries",
   "description": "Data rate per Edge Node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ran_autoscaler_desired_replicas",
     "legendFormat": "desired {{edge_node}}"
    },
    {
     "expr": "ran_autoscaler_current_replicas",
     "legendFormat": "current {{edge_node}}"
    }
   ]
  }
 ]
}